# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'csv_to_txt_formatter.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setStyleSheet("background-color: rgb(240,240,255);")
        self.input_field = QtWidgets.QLineEdit(Form)
        self.input_field.setGeometry(QtCore.QRect(20, 50, 361, 20))
        self.input_field.setObjectName("input_field")
        self.output_field = QtWidgets.QLineEdit(Form)
        self.output_field.setGeometry(QtCore.QRect(20, 120, 361, 20))
        self.output_field.setObjectName("output_field")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(60, 212, 281, 41))
        self.pushButton.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"color: ;\n"
"color: rgb(255, 255, 255);\n"
"padding: 10px;\n"
"border: none;\n"
"border-radius: 4px;\n"
"font-weight: bold;\n"
"font-size: 17px;")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 30, 251, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 231, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 241, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.run) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "csv to txt Formater"))
        self.pushButton.setText(_translate("Form", "Convert File"))
        self.label.setText(_translate("Form", "CSV Filepath (Including File Name):"))
        self.label_2.setText(_translate("Form", "Output Filepath"))
        self.label_3.setText(_translate("Form", "Use double slash for all slashes"))
